AttributeError in validator.py:VMessageRecipient
AttributeError: 'NoneType' object has no attribute '_id'(b412c68f4d2e201e4f4c4a459776dafe)
Introduced after blacklist push.